# Generated by Django 4.2 on 2023-04-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={},
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(default='Horror', max_length=100),
            preserve_default=False,
        ),
    ]
