# Generated by Django 4.2 on 2023-04-25 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_rename_number_of_chapters_book_chapters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
